import JobNoteStatus from '../JobNoteStatus.jsx';
import React, {useEffect,useMemo,useRef,useState} from 'react';
import {AREAS,ROLES,CONDITIONS,PRIORITIES,SYMPTOMS,SCOPE,estimateAge,conditionSummary} from './model.js';
import {STATUS_LABELS} from '../../recallCheck.js';
import {inspectionDraft,preparePhoto} from './draft.js';
import './inspection.css';
const identityLabels={manufacturer:'Manufacturer / brand',productFamily:'Product family',model:'Panel model / catalog number',dateCode:'Manufacturing date code',serialNumber:'Serial number',plantCode:'Plant code'};
const newDraft=()=>({id:`INS-${Date.now()}-${crypto.randomUUID()}`,stage:0,panelName:'Main Panel',job:null,photos:[],skippedPhotos:{interior:'',label:'',surroundings:''},identity:Object.fromEntries(Object.keys(identityLabels).map(k=>[k,''])),identificationReviewed:false,ageEvidence:{mode:'unknown',component:'unknown',verified:false,yearFrom:'',yearTo:'',sourceNote:'',sourceUrl:''},installation:{year:'',evidence:''},findings:[],coverage:Object.fromEntries(Object.keys(AREAS).map(k=>[k,{status:'pending',reason:''}])),symptoms:Object.fromEntries(Object.keys(SYMPTOMS).map(k=>[k,''])),symptomNotes:'',qualityWarnings:[],qualityReviews:{},analysis:null,analysisEvidence:'',recall:null,recallEvidence:'',notes:'',reportReviewed:false,officeReview:false});
async function api(url,options){const r=await fetch(url,options);if(r.status===401||!r.headers.get('content-type')?.includes('application/json'))throw new Error('Please sign in again from the app home page. Your saved draft stays on this device.');const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed. Please retry.');return d;}
function Header(){return <header className="topbar"><a className="brand" href="/"><span className="bolt">⚡</span><span><strong>GEN3</strong><small>Panel Inspection</small></span></a><a className="piHeaderLink" href="/panel-inspection/history">History</a></header>;}
function Badge({summary}){return <div className={`piBadge ${summary.condition}`}><strong>{CONDITIONS[summary.condition]}</strong>{!summary.complete&&<span>Incomplete scope / review</span>}</div>;}
function Photo({photo,findings=[],selected,onSelect,onPlace,placeMode=false}){
 const url=useMemo(()=>photo.file?URL.createObjectURL(photo.file):photo.url,[photo.file,photo.url]);useEffect(()=>()=>{if(photo.file)URL.revokeObjectURL(url);},[url]);
 return <figure className="piPhoto"><div className={`piPhotoFrame ${placeMode?'placing':''}`} onClick={event=>{if(!placeMode)return;const rect=event.currentTarget.getBoundingClientRect();onPlace?.((event.clientX-rect.left)/rect.width*100,(event.clientY-rect.top)/rect.height*100);}}><img src={url} alt={ROLES[photo.role]} />{findings.filter(f=>f.photoId===photo.id&&f.status!=='dismissed'&&f.x!==null&&f.y!==null).map(f=><button className={`piMarker ${selected===f.id?'active':''}`} style={{left:`${f.x}%`,top:`${f.y}%`}} key={f.id} type="button" aria-label={`Finding ${f.number}: ${f.title}`} onClick={e=>{e.stopPropagation();onSelect?.(f.id);}}>{f.number}</button>)}</div><figcaption>{ROLES[photo.role]} <a href={url} target="_blank" rel="noreferrer">Enlarge</a></figcaption></figure>;
}
function AgeCard({age}){return <div className="piAge"><span className="piSmall">MANUFACTURING EVIDENCE</span><strong>{age.label}</strong>{age.ageLabel&&<span>{age.ageLabel}</span>}<p>{age.reason}</p>{age.evidence&&<p>{age.evidence}</p>}{age.sourceUrl&&<a href={age.sourceUrl} target="_blank" rel="noreferrer">View age reference ↗</a>}</div>;}
function RecallResult({recall}){return <div className="piRecall"><strong>Recall status: {recall?STATUS_LABELS[recall.status]:'Not checked'}</strong><p>{recall?recall.message:'Recall status is separate from the visual condition review.'}</p>{recall&&<><small>Checked {new Date(recall.checkedAt).toLocaleString()}</small>{recall.notices.map(n=><p key={n.id}><a href={n.url} target="_blank" rel="noreferrer">#{n.number} · {n.title} ↗</a></p>)}</>}</div>;}
function History(){const [items,setItems]=useState([]),[next,setNext]=useState(null),[q,setQ]=useState(''),[reviewOnly,setReviewOnly]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[incomplete,setIncomplete]=useState(0);
 async function load(cursor){setBusy(true);setError('');try{const d=await api(`/api/panel-inspections${cursor?`?cursor=${encodeURIComponent(cursor)}`:''}`);setItems(old=>cursor?[...old,...d.records]:d.records);setNext(d.next);setIncomplete(old=>(cursor?old:0)+d.incomplete);}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);const filtered=items.filter(r=>(!reviewOnly||r.summary.needsOfficeReview)&&[r.panelName,r.job?.id,r.job?.customer,r.job?.address,r.identity.manufacturer,r.identity.model,r.reviewedBy].join(' ').toLowerCase().includes(q.toLowerCase()));
 return <><Header/><main className="piPage"><p className="eyebrow">Permanent panel records</p><h1>Inspection history</h1><a className="primary piLink" href="/panel-inspection">Start or resume an inspection</a><label>Search loaded inspections<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Customer, address, panel, or technician"/></label><label className="piCheck"><input type="checkbox" checked={reviewOnly} onChange={e=>setReviewOnly(e.target.checked)}/>Needs office review only</label>{error&&<div role="alert" className="piError">{error}<button className="secondary" onClick={()=>load(next)}>Retry</button></div>}{incomplete>0&&<p>{incomplete} inspection records could not be read or have unfinished uploads. Refresh to retry.</p>}{filtered.map(r=><a className="piCard piHistoryCard" href={`/panel-inspection?id=${encodeURIComponent(r.id)}`} key={r.id}><Badge summary={r.summary}/><h2>{r.panelName}</h2><p>{r.job?.customer||'Standalone inspection'}{r.job?.id?` · Job #${r.job.id}`:''}<br/>{r.job?.address}</p><p>{r.age.label}</p><small>{new Date(r.savedAt).toLocaleString()} · {r.reviewedBy}</small></a>)}{busy&&<p role="status">Loading inspections…</p>}{!busy&&!error&&!filtered.length&&<p>No inspections found among the loaded records.</p>}{next&&<button className="secondary" disabled={busy} onClick={()=>load(next)}>Load more inspections</button>}<p className="piMuted">{items.length} inspections loaded{next?' · Older records available with Load more.':''}</p><a href="/">Back to app home</a></main></>;
}
function Saved({record}){const [selected,setSelected]=useState('');const findings=record.findings.map((f,i)=>({...f,number:i+1}));return <><p className="eyebrow">Saved technician review · First version</p><h1>{record.panelName}</h1><p className="lead compact">{record.job?.customer||'Standalone inspection'}{record.job?.id?` · Job #${record.job.id}`:''}<br/>{record.job?.address}</p><Badge summary={record.summary}/><p className="piMuted">Reviewed by {record.reviewedBy.name} · {new Date(record.savedAt).toLocaleString()}</p><div className="piActions"><a className="primary piLink" href={record.pdfUrl} target="_blank" rel="noreferrer">Open / download customer report</a><a className="secondary piLink" href="/panel-inspection">New inspection</a></div><JobNoteStatus endpoint={`/api/panel-inspections/${encodeURIComponent(record.id)}/job-note`} initial={record.jobNote}/><AgeCard age={record.age}/><RecallResult recall={record.recall}/><div className="piCard"><h2>Photos and findings</h2><div className="piGallery">{record.photos.map(p=><Photo key={p.id} photo={p} findings={findings} selected={selected} onSelect={id=>{setSelected(id);document.getElementById(`finding-${id}`)?.scrollIntoView({behavior:'smooth',block:'center'});}}/>)}</div>{findings.map(f=><article id={`finding-${f.id}`} className={`piFinding ${selected===f.id?'selected':''}`} key={f.id}><h3>{f.number}. {f.title}</h3><strong>{f.status==='confirmed'?'Technician confirmed':f.status==='dismissed'?'Dismissed with reason':'Unverified — needs review'} · {PRIORITIES[f.priority]}</strong><p>{f.observation}</p><p>Next step: {f.recommendation||'Pending'}</p><p>Review evidence: {f.reviewNote||'Pending'}</p></article>)}{!findings.length&&<p>No findings recorded. The inspection scope and limitations still apply.</p>}</div><div className="piCard"><h2>Scope and notes</h2>{Object.entries(AREAS).map(([k,label])=><p key={k}><strong>{label}:</strong> {record.coverage[k].status.replace('_',' ')}{record.coverage[k].reason?` — ${record.coverage[k].reason}`:''}</p>)}{record.notes&&<p>{record.notes}</p>}<p>{record.scope}</p></div><a href="/panel-inspection/history">Back to inspection history</a></>;}
export default function PanelInspection(){return window.location.pathname.endsWith('/history')?<History/>:<Inspection/>;}
function Inspection(){
 const recordId=new URLSearchParams(window.location.search).get('id');
 const [draft,setDraft]=useState(null),[saved,setSaved]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[draftState,setDraftState]=useState(''),[online,setOnline]=useState(navigator.onLine),[selected,setSelected]=useState(''),[placing,setPlacing]=useState(false);
 const [jobs,setJobs]=useState([]),[jobQuery,setJobQuery]=useState(''),[jobDate,setJobDate]=useState(()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);}),[jobsBusy,setJobsBusy]=useState(false),[jobError,setJobError]=useState('');
 const sequence=useRef(Promise.resolve()),current=useRef(null);current.current=draft;
 const patch=changes=>setDraft(old=>({...old,...changes,reportReviewed:changes.reportReviewed===true}));
 useEffect(()=>{let active=true;if(recordId)api(`/api/panel-inspections/${encodeURIComponent(recordId)}`).then(r=>active&&setSaved(r)).catch(e=>active&&setError(e.message));else inspectionDraft('get').then(r=>active&&setDraft(r||newDraft())).catch(()=>{if(active){setDraft(newDraft());setError('Local draft storage is unavailable. Keep this page open until saving is complete.');}});const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{active=false;window.removeEventListener('online',on);window.removeEventListener('offline',off);};},[recordId]);
 useEffect(()=>{if(!draft||saved)return;setDraftState('Saving draft on this device…');sequence.current=sequence.current.catch(()=>{}).then(()=>inspectionDraft('put',draft));sequence.current.then(()=>{if(current.current===draft)setDraftState('Draft saved on this device');}).catch(()=>setDraftState('Draft could not be saved. Keep this page open.'));},[draft,saved]);
 useEffect(()=>{const warn=e=>{if(busy||draftState.includes('Saving')||draftState.includes('could not')){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[busy,draftState]);
 async function run(label,fn){setBusy(label);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy('');}}
 function form(){const f=new FormData();draft.photos.forEach(p=>f.append('photos',p.file,p.file.name));f.append('record',JSON.stringify({...draft,photos:draft.photos.map(({id,role})=>({id,role}))}));return f;}
 function resetPhotoReview(photos){if((draft.analysisEvidence||draft.findings.length)&&!window.confirm('Changing photos clears the current findings and review so the new evidence can be assessed. Continue?'))return;patch({photos,findings:[],analysis:null,analysisEvidence:'',qualityWarnings:[],qualityReviews:{},coverage:newDraft().coverage,identificationReviewed:false,recall:null,recallEvidence:''});setSelected('');}
 async function addPhoto(role,file){await run('Preparing photo…',async()=>{const prepared=await preparePhoto(file);const retained=role==='detail'?draft.photos:draft.photos.filter(p=>p.role!==role);if(retained.length>=10)throw new Error('Use up to ten photos per inspection.');resetPhotoReview([...retained,{id:`p-${crypto.randomUUID()}`,role,file:prepared}]);});}
 async function analyze(){if(draft.findings.length&&!window.confirm('A new AI review replaces the current findings. Continue?'))return;await run('Reviewing panel photos. This may take a minute…',async()=>{const data=await api('/api/panel-inspections/analyze',{method:'POST',body:form()});patch({analysis:data.analysis,analysisEvidence:data.analysisEvidence,identity:data.analysis.identity,findings:data.analysis.findings,qualityWarnings:data.analysis.qualityWarnings,qualityReviews:{},identificationReviewed:false,ageEvidence:{...draft.ageEvidence,mode:'date_code',component:data.analysis.dateCodeComponent,verified:false},recall:null,recallEvidence:'',stage:1});setSelected(data.analysis.findings[0]?.id||'');});}
 async function lookup(){await run('Checking official recall notices…',async()=>{const data=await api('/api/recall-checks/lookup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identification:draft.identity,reviewed:draft.identificationReviewed})});patch({recall:data.snapshot,recallEvidence:data.evidence});});}
 async function save(){await run('Saving the inspection, photos, and PDF report…',async()=>{const r=await api('/api/panel-inspections',{method:'POST',body:form()});setSaved(r);await sequence.current.catch(()=>{});await inspectionDraft('delete').catch(()=>{});window.history.replaceState(null,'',`/panel-inspection?id=${encodeURIComponent(r.id)}`);window.scrollTo(0,0);});}
 async function loadJobs(){setJobsBusy(true);setJobError('');try{const data=await api(`/api/servicetitan/jobs?date=${jobDate}`);setJobs(data.jobs||[]);if(!data.jobs?.length)setJobError('No appointments for this date. You may continue without a job link.');}catch(e){setJobError(e.message);}finally{setJobsBusy(false);}}
 const summary=draft?conditionSummary(draft):null;
 const age=draft?estimateAge(draft.identity,draft.ageEvidence):null;
 const photosReady=draft?.photos.some(p=>p.role==='overview')&&['interior','label','surroundings'].every(role=>draft.photos.some(p=>p.role===role)||draft.skippedPhotos[role]?.trim());
 const numbered=draft?.findings.map((f,i)=>({...f,number:i+1}))||[];
 const activeFinding=draft?.findings.find(f=>f.id===selected);
 const updateFinding=(id,changes)=>patch({findings:draft.findings.map(f=>f.id===id?{...f,...changes}:f)});
 function addFinding(){const f={id:`tech-${crypto.randomUUID()}`,source:'technician',title:'',observation:'',recommendation:'',category:'enclosure',priority:'attention',status:'pending',reviewNote:'',photoId:draft.photos[0]?.id||'',x:null,y:null};patch({findings:[...draft.findings,f]});setSelected(f.id);setPlacing(false);}
 const invalidFindings=draft?.findings.some(f=>!f.title.trim()||!f.observation.trim()||f.status!=='pending'&&(f.reviewNote.trim().length<10||f.status==='confirmed'&&!f.recommendation.trim()));
 return <><Header/><main className="piPage">{error&&<div className="piError" role="alert">{error}</div>}{saved?<Saved record={saved}/>:!draft?(!error&&<p>Loading inspection…</p>):<>
  <p className="eyebrow">First version · Field trial</p><h1>Panel inspection</h1><p className="lead compact">Build a visual record, review the findings, and explain the next steps.</p><nav className="piSteps" aria-label="Inspection progress">{['Capture','Identity & scope','Review & report'].map((s,i)=><button type="button" disabled={!!busy||i>0&&!photosReady} aria-current={draft.stage===i?'step':undefined} key={s} onClick={()=>{patch({stage:i});setPlacing(false);}}>{i+1}. {s}</button>)}</nav>
  <p className="piMuted" role="status">{draftState}{!online?' · Offline — photos and notes can be captured; AI, recalls, and shared saving need internet.':''}</p>{busy&&<div className="piBusy" role="status">{busy}</div>}
  <fieldset disabled={!!busy} className="piFieldset">
  {draft.stage===0&&<>
   <section className="piCard"><h2>Panel and job</h2><label>Panel name<input value={draft.panelName} maxLength={200} onChange={e=>patch({panelName:e.target.value})}/></label><details><summary>{draft.job?`Job #${draft.job.id} · ${draft.job.customer}`:'Link a ServiceTitan job (optional)'}</summary>{draft.job&&<p>{draft.job.address} <button type="button" className="piTextButton" onClick={()=>patch({job:null})}>Remove link</button></p>}<div className="piInline"><label>Appointment date<input type="date" value={jobDate} onChange={e=>{setJobDate(e.target.value);setJobs([]);}}/></label><button type="button" className="secondary" disabled={jobsBusy||!online} onClick={loadJobs}>{jobsBusy?'Loading…':'Load jobs'}</button></div>{jobError&&<p>{jobError}</p>}{jobs.length>0&&<><label>Find job<input value={jobQuery} onChange={e=>setJobQuery(e.target.value)} placeholder="Name, address, or number"/></label><div className="piJobList">{jobs.filter(j=>[j.id,j.customer,j.address].join(' ').toLowerCase().includes(jobQuery.toLowerCase())).map(j=><button type="button" className="piJob" key={j.serviceTitanId||j.id} onClick={()=>patch({job:j})}><strong>{j.customer} · #{j.id}</strong><span>{j.address}</span></button>)}</div></>}</details></section>
   <section className="piCard"><h2>Guided photos</h2><p>Capture accessible views using GEN3's normal electrical work procedures. If a view cannot be obtained safely, record why it is unavailable.</p>{['overview','interior','label','surroundings'].map(role=><div className="piPhotoStep" key={role}><h3>{ROLES[role]}</h3><p className="piMuted">{{overview:'Show the complete panel and cover.',interior:'A qualified technician captures visible interior wiring and components when safe to access.',label:'Get the model and date-code label in focus. Keep breaker and cover dates separate.',surroundings:'Show the working area and approach to the panel.'}[role]}</p>{draft.photos.filter(p=>p.role===role).map(p=><Photo photo={p} key={p.id}/>)}<label className="secondary piPhotoInput">{draft.photos.some(p=>p.role===role)?'Replace':'Take / select'} {ROLES[role].toLowerCase()}<input type="file" accept="image/*" capture="environment" aria-label={`Add ${role} photo`} onChange={e=>{const file=e.target.files?.[0];if(file)addPhoto(role,file);e.target.value='';}}/></label>{role!=='overview'&&!draft.photos.some(p=>p.role===role)&&<label>Unavailable reason<input value={draft.skippedPhotos[role]} onChange={e=>patch({skippedPhotos:{...draft.skippedPhotos,[role]:e.target.value}})} placeholder="Missing label, cannot safely access, obstructed…"/></label>}</div>)}<h3>Concern close-ups</h3><div className="piGallery">{draft.photos.filter(p=>p.role==='detail').map(p=><div key={p.id}><Photo photo={p}/><button className="piTextButton" type="button" onClick={()=>resetPhotoReview(draft.photos.filter(v=>v.id!==p.id))}>Remove close-up</button></div>)}</div><label className="secondary piPhotoInput">Add close-up ({draft.photos.length}/10 photos)<input type="file" accept="image/*" capture="environment" aria-label="Add detail photo" disabled={draft.photos.length>=10} onChange={e=>{const file=e.target.files?.[0];if(file)addPhoto('detail',file);e.target.value='';}}/></label></section>
   <section className="piCard"><h2>Reported symptoms</h2><p>Ask the homeowner or record the technician's observations. Unknown is an acceptable answer.</p>{Object.entries(SYMPTOMS).map(([key,label])=><label key={key}>{label}<select value={draft.symptoms[key]} onChange={e=>patch({symptoms:{...draft.symptoms,[key]:e.target.value}})}><option value="">Not recorded</option><option value="yes">Yes</option><option value="no">No</option><option value="unknown">Unknown</option></select></label>)}<label>Symptom details<textarea value={draft.symptomNotes} maxLength={2000} onChange={e=>patch({symptomNotes:e.target.value})}/></label></section>
   <div className="piActions"><button type="button" className="primary" disabled={!photosReady||!online} onClick={analyze}>Review photos with AI</button><button type="button" className="secondary" disabled={!photosReady} onClick={()=>patch({stage:1})}>Continue with manual review</button></div>
  </>}
  {draft.stage===1&&<>
   <section className="piCard"><h2>Confirm panel identification</h2><p>AI readings are suggestions. Check them against the label and leave unreadable fields blank.</p><div className="piGallery">{draft.photos.filter(p=>p.role==='label').map(p=><Photo key={p.id} photo={p}/>)}</div><div className="piGrid">{Object.entries(identityLabels).map(([key,label])=><label key={key}>{label}<input value={draft.identity[key]||''} maxLength={200} autoCorrect="off" onChange={e=>patch({identity:{...draft.identity,[key]:e.target.value},identificationReviewed:false,ageEvidence:{...draft.ageEvidence,verified:false},recall:null,recallEvidence:''})}/></label>)}</div><label className="piCheck"><input type="checkbox" checked={draft.identificationReviewed} onChange={e=>patch({identificationReviewed:e.target.checked})}/>I checked the readings and left unavailable details blank.</label></section>
   <section className="piCard"><h2>Manufacturing age</h2><label>Evidence method<select value={draft.ageEvidence.mode} onChange={e=>patch({ageEvidence:{...draft.ageEvidence,mode:e.target.value,verified:false}})}><option value="unknown">Unknown / no reliable evidence</option><option value="date_code">Decode a verified panel date code</option><option value="documented_range">Documented year or production range</option></select></label>{draft.ageEvidence.mode==='date_code'&&<><label>The date code belongs to<select value={draft.ageEvidence.component} onChange={e=>patch({ageEvidence:{...draft.ageEvidence,component:e.target.value,verified:false}})}><option value="unknown">Unknown component</option><option value="enclosure">Panel enclosure / box label</option><option value="interior">Panel interior label</option><option value="breaker">Individual breaker</option><option value="cover">Removable cover / trim</option></select></label><p className="piMuted">First-version automatic decoding: modern Square D QO / Homeline six-digit panel codes. Other formats stay unknown until supported by documentation.</p></>}{draft.ageEvidence.mode==='documented_range'&&<><div className="piGrid">{[['yearFrom','Manufacturing year from'],['yearTo','Manufacturing year to']].map(([key,label])=><label key={key}>{label}<input inputMode="numeric" maxLength={4} value={draft.ageEvidence[key]} onChange={e=>patch({ageEvidence:{...draft.ageEvidence,[key]:e.target.value,verified:false}})}/></label>)}</div><label>Documentary evidence<textarea value={draft.ageEvidence.sourceNote} maxLength={2000} placeholder="Manufacturer records, a dated original label, or a documented production period. Appearance alone is insufficient." onChange={e=>patch({ageEvidence:{...draft.ageEvidence,sourceNote:e.target.value,verified:false}})}/></label><label>Reference URL (optional)<input type="url" value={draft.ageEvidence.sourceUrl} onChange={e=>patch({ageEvidence:{...draft.ageEvidence,sourceUrl:e.target.value,verified:false}})}/></label></>}{draft.ageEvidence.mode!=='unknown'&&<label className="piCheck"><input type="checkbox" checked={draft.ageEvidence.verified} onChange={e=>patch({ageEvidence:{...draft.ageEvidence,verified:e.target.checked}})}/>I verified this manufacturing evidence and its component.</label>}<AgeCard age={age}/><details><summary>Separate installation date (optional)</summary><label>Installation year<input inputMode="numeric" maxLength={4} value={draft.installation.year} onChange={e=>patch({installation:{...draft.installation,year:e.target.value}})}/></label><label>Installation-date evidence<textarea value={draft.installation.evidence} onChange={e=>patch({installation:{...draft.installation,evidence:e.target.value}})} placeholder="Job record, permit, or other evidence"/></label></details></section>
   <section className="piCard"><h2>Inspection scope</h2><p>Mark each area actually reviewed. Missing views and unreviewed areas keep the scope incomplete.</p>{Object.entries(AREAS).map(([key,label])=><div className="piScopeRow" key={key}><label>{label}<select value={draft.coverage[key].status} onChange={e=>patch({coverage:{...draft.coverage,[key]:{...draft.coverage[key],status:e.target.value}}})}><option value="pending">Pending</option><option value="reviewed">Reviewed within visible scope</option><option value="not_inspected">Not inspected</option></select></label>{draft.coverage[key].status==='not_inspected'&&<label>Reason<input value={draft.coverage[key].reason} onChange={e=>patch({coverage:{...draft.coverage,[key]:{...draft.coverage[key],reason:e.target.value}}})}/></label>}</div>)}</section>
   {draft.qualityWarnings.length>0&&<section className="piCard"><h2>Photo limitations</h2>{draft.qualityWarnings.map((w,i)=><div key={i}><p>{w.reason}</p><label>Technician response<input value={draft.qualityReviews[w.photoId]||''} onChange={e=>patch({qualityReviews:{...draft.qualityReviews,[w.photoId]:e.target.value}})} placeholder="What could be reviewed? What remains outside scope?"/></label></div>)}</section>}
   <section className="piCard"><h2>Official recall check</h2><RecallResult recall={draft.recall}/><button type="button" className="secondary" disabled={!online||!draft.identificationReviewed} onClick={lookup}>Check official recalls</button><p className="piMuted">Possible recalls remain possible here. Use the separate Recall Check workflow to document a confirmed match or exclusion.</p></section><div className="piActions"><button className="secondary" type="button" onClick={()=>patch({stage:0})}>Back to capture</button><button className="primary" type="button" onClick={()=>patch({stage:2})}>Review findings and report</button></div>
  </>}
  {draft.stage===2&&<>
   <section className="piCard"><Badge summary={summary}/><p>{summary.confirmed} confirmed finding{summary.confirmed===1?'':'s'} · {summary.pending} needing review</p>{summary.pendingUrgent&&<p className="piError">An unverified urgent concern needs prompt technician review.</p>}{!summary.complete&&<p className="piMuted">Incomplete: {summary.missingPhotos.length} missing views, {summary.missingAreas.length} areas not reviewed, {summary.pending} pending findings, {summary.qualityPending} photo limitations awaiting a response{!draft.identificationReviewed?', label readings not confirmed':''}{summary.unansweredSymptoms.length?`, ${summary.unansweredSymptoms.length} symptom questions unanswered`:''}.</p>}{summary.symptomConcerns.length>0&&<p>Reported symptoms needing attention: {summary.symptomConcerns.map(k=>SYMPTOMS[k]).join(', ')}.</p>}<p className="piMuted">{SCOPE}</p></section>
   <section className="piCard"><div className="piSectionHeader"><h2>Photo findings</h2><button type="button" className="secondary" onClick={addFinding} disabled={draft.findings.length>=60}>Add finding</button></div><p>Confirm, correct, or dismiss every suggestion. Tap a numbered marker to select its finding.</p><div className="piGallery">{draft.photos.map(p=><Photo key={p.id} photo={p} findings={numbered} selected={selected} onSelect={id=>{setSelected(id);setPlacing(false);document.getElementById(`edit-${id}`)?.scrollIntoView({behavior:'smooth',block:'center'});}} placeMode={placing&&activeFinding?.photoId===p.id} onPlace={(x,y)=>{updateFinding(selected,{x,y});setPlacing(false);}}/>)}</div>{placing&&<p role="status" className="piCallout">Tap the selected finding's photo to position its numbered marker.</p>}{!draft.findings.length&&<p>No AI concerns were proposed or no AI review was run. Add any technician findings and complete the inspection scope.</p>}
    {numbered.map(f=><details id={`edit-${f.id}`} key={f.id} className={`piFinding ${selected===f.id?'selected':''}`} open={selected===f.id} onToggle={e=>{if(e.currentTarget.open&&selected!==f.id)setSelected(f.id);}}><summary onClick={e=>{e.preventDefault();setSelected(selected===f.id?'':f.id);setPlacing(false);}}>{f.number}. {f.title||'New finding'} <span>{f.status==='pending'?'Needs review':f.status==='confirmed'?'Confirmed':'Dismissed'}</span></summary><div className="piGrid"><label>Finding title<input value={f.title} maxLength={160} onChange={e=>updateFinding(f.id,{title:e.target.value})}/></label><label>Inspection area<select value={f.category} onChange={e=>updateFinding(f.id,{category:e.target.value})}>{Object.entries(AREAS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><label>Visible observation<textarea value={f.observation} maxLength={1800} onChange={e=>updateFinding(f.id,{observation:e.target.value,status:'pending'})}/></label><label>Suggested next step<textarea value={f.recommendation} maxLength={1200} onChange={e=>updateFinding(f.id,{recommendation:e.target.value})}/></label><div className="piGrid"><label>Action priority<select value={f.priority} onChange={e=>updateFinding(f.id,{priority:e.target.value,status:'pending'})}>{Object.entries(PRIORITIES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Technician finding<select value={f.status} onChange={e=>updateFinding(f.id,{status:e.target.value})}><option value="pending">Needs review</option><option value="confirmed">Confirmed by technician</option><option value="dismissed">Dismissed with reason</option></select></label></div><label>Review evidence / dismissal reason<textarea value={f.reviewNote} maxLength={1800} onChange={e=>updateFinding(f.id,{reviewNote:e.target.value})} placeholder="What did you verify on site? Explain any correction or dismissal."/></label><label>Evidence photo<select value={f.photoId} onChange={e=>updateFinding(f.id,{photoId:e.target.value,x:null,y:null,status:'pending'})}><option value="">No photo — describe direct observation in review notes</option>{draft.photos.map((p,i)=><option key={p.id} value={p.id}>{i+1}. {ROLES[p.role]}</option>)}</select></label><div className="piActions"><button className="secondary" type="button" disabled={!f.photoId} onClick={()=>{setSelected(f.id);setPlacing(true);document.querySelector('.piGallery')?.scrollIntoView({behavior:'smooth'});}}>Place / move photo marker</button><button className="secondary" type="button" onClick={()=>updateFinding(f.id,{x:null,y:null})}>Remove marker</button></div></details>)}
   </section><section className="piCard"><h2>Report preview</h2><AgeCard age={age}/><RecallResult recall={draft.recall}/><label>Technician recommendations / notes<textarea value={draft.notes} maxLength={4000} onChange={e=>patch({notes:e.target.value})}/></label><label className="piCheck"><input type="checkbox" checked={draft.officeReview} onChange={e=>patch({officeReview:e.target.checked})}/>Request office review</label>{summary.needsOfficeReview&&<p className="piCallout">This record will appear in the “Needs office review” history filter. No notification is sent automatically.</p>}<label className="piCheck"><input type="checkbox" checked={draft.reportReviewed} onChange={e=>patch({reportReviewed:e.target.checked})}/>I reviewed the report and its limitations. My confirmed findings and recommendations reflect my inspection.</label>{!summary.complete&&<p>Saving is allowed for follow-up. The PDF will clearly show the incomplete scope and any unverified findings.</p>}{invalidFindings&&<p className="piError">Every finding needs a title and observation. Confirmed or dismissed findings need an evidence note of at least 10 characters; confirmed findings also need a next step.</p>}<div className="piActions"><button className="secondary" type="button" onClick={()=>patch({stage:1})}>Back to identity and scope</button><button className="primary" type="button" disabled={!online||!draft.reportReviewed||invalidFindings} onClick={save}>Save inspection and PDF</button></div></section>
  </>}
  </fieldset><footer className="piFooter"><a href="/">App home</a><a href="/recall-check">Quick Recall Check</a><button className="piTextButton" type="button" disabled={!!busy} onClick={async()=>{if(window.confirm('Discard this unsaved inspection and its draft photos?')){await sequence.current.catch(()=>{});setDraft(newDraft());setSelected('');setError('');}}}>Discard draft</button></footer>
 </>}</main></>;
}
